"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.entity_ref import EntityRef
globals()['EntityRef'] = EntityRef
from openziti_edge_management.model.service_config_detail import ServiceConfigDetail


class TestServiceConfigDetail(unittest.TestCase):
    """ServiceConfigDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceConfigDetail(self):
        """Test ServiceConfigDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceConfigDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
