"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.api_error import ApiError
from openziti_edge_management.model.api_error_args import ApiErrorArgs
from openziti_edge_management.model.api_field_error import ApiFieldError
globals()['ApiError'] = ApiError
globals()['ApiErrorArgs'] = ApiErrorArgs
globals()['ApiFieldError'] = ApiFieldError
from openziti_edge_management.model.api_error_cause import ApiErrorCause


class TestApiErrorCause(unittest.TestCase):
    """ApiErrorCause unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiErrorCause(self):
        """Test ApiErrorCause"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiErrorCause()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
