"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.base_entity import BaseEntity
from openziti_edge_management.model.entity_ref import EntityRef
from openziti_edge_management.model.links import Links
from openziti_edge_management.model.tags import Tags
from openziti_edge_management.model.terminator_cost import TerminatorCost
from openziti_edge_management.model.terminator_detail_all_of import TerminatorDetailAllOf
from openziti_edge_management.model.terminator_precedence import TerminatorPrecedence
globals()['BaseEntity'] = BaseEntity
globals()['EntityRef'] = EntityRef
globals()['Links'] = Links
globals()['Tags'] = Tags
globals()['TerminatorCost'] = TerminatorCost
globals()['TerminatorDetailAllOf'] = TerminatorDetailAllOf
globals()['TerminatorPrecedence'] = TerminatorPrecedence
from openziti_edge_management.model.terminator_detail import TerminatorDetail


class TestTerminatorDetail(unittest.TestCase):
    """TerminatorDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTerminatorDetail(self):
        """Test TerminatorDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TerminatorDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
