"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.operating_system import OperatingSystem
from openziti_edge_management.model.posture_check_failure import PostureCheckFailure
from openziti_edge_management.model.posture_check_failure_operating_system_actual import PostureCheckFailureOperatingSystemActual
from openziti_edge_management.model.posture_check_failure_operating_system_all_of import PostureCheckFailureOperatingSystemAllOf
globals()['OperatingSystem'] = OperatingSystem
globals()['PostureCheckFailure'] = PostureCheckFailure
globals()['PostureCheckFailureOperatingSystemActual'] = PostureCheckFailureOperatingSystemActual
globals()['PostureCheckFailureOperatingSystemAllOf'] = PostureCheckFailureOperatingSystemAllOf
from openziti_edge_management.model.posture_check_failure_operating_system import PostureCheckFailureOperatingSystem


class TestPostureCheckFailureOperatingSystem(unittest.TestCase):
    """PostureCheckFailureOperatingSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckFailureOperatingSystem(self):
        """Test PostureCheckFailureOperatingSystem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckFailureOperatingSystem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
