"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.dial_bind import DialBind
from openziti_edge_management.model.entity_ref import EntityRef
from openziti_edge_management.model.links import Links
from openziti_edge_management.model.session_detail import SessionDetail
from openziti_edge_management.model.session_edge_router import SessionEdgeRouter
from openziti_edge_management.model.session_management_detail_all_of import SessionManagementDetailAllOf
from openziti_edge_management.model.tags import Tags
globals()['DialBind'] = DialBind
globals()['EntityRef'] = EntityRef
globals()['Links'] = Links
globals()['SessionDetail'] = SessionDetail
globals()['SessionEdgeRouter'] = SessionEdgeRouter
globals()['SessionManagementDetailAllOf'] = SessionManagementDetailAllOf
globals()['Tags'] = Tags
from openziti_edge_management.model.session_management_detail import SessionManagementDetail


class TestSessionManagementDetail(unittest.TestCase):
    """SessionManagementDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionManagementDetail(self):
        """Test SessionManagementDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionManagementDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
