"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.identity_detail import IdentityDetail
globals()['IdentityDetail'] = IdentityDetail
from openziti_edge_management.model.identity_list import IdentityList


class TestIdentityList(unittest.TestCase):
    """IdentityList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityList(self):
        """Test IdentityList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentityList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
