"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.config_types import ConfigTypes
from openziti_edge_management.model.env_info import EnvInfo
from openziti_edge_management.model.password import Password
from openziti_edge_management.model.sdk_info import SdkInfo
from openziti_edge_management.model.username import Username
globals()['ConfigTypes'] = ConfigTypes
globals()['EnvInfo'] = EnvInfo
globals()['Password'] = Password
globals()['SdkInfo'] = SdkInfo
globals()['Username'] = Username
from openziti_edge_management.model.authenticate import Authenticate


class TestAuthenticate(unittest.TestCase):
    """Authenticate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticate(self):
        """Test Authenticate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Authenticate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
