"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.enrollment_detail import EnrollmentDetail
from openziti_edge_management.model.meta import Meta
globals()['EnrollmentDetail'] = EnrollmentDetail
globals()['Meta'] = Meta
from openziti_edge_management.model.detail_enrollment_envelope import DetailEnrollmentEnvelope


class TestDetailEnrollmentEnvelope(unittest.TestCase):
    """DetailEnrollmentEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailEnrollmentEnvelope(self):
        """Test DetailEnrollmentEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailEnrollmentEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
