"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.dial_bind import DialBind
from openziti_edge_management.model.policy_failure import PolicyFailure
globals()['DialBind'] = DialBind
globals()['PolicyFailure'] = PolicyFailure
from openziti_edge_management.model.failed_service_request import FailedServiceRequest


class TestFailedServiceRequest(unittest.TestCase):
    """FailedServiceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFailedServiceRequest(self):
        """Test FailedServiceRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FailedServiceRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
