"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.posture_checks_failure_mfa_values import PostureChecksFailureMfaValues


class TestPostureChecksFailureMfaValues(unittest.TestCase):
    """PostureChecksFailureMfaValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureChecksFailureMfaValues(self):
        """Test PostureChecksFailureMfaValues"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureChecksFailureMfaValues()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
