"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_management
from openziti_edge_management.api.router_api import RouterApi  # noqa: E501


class TestRouterApi(unittest.TestCase):
    """RouterApi unit test stubs"""

    def setUp(self):
        self.api = RouterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_router(self):
        """Test case for create_router

        Create a router resource  # noqa: E501
        """
        pass

    def test_create_transit_router(self):
        """Test case for create_transit_router

        Create a router resource  # noqa: E501
        """
        pass

    def test_delete_router(self):
        """Test case for delete_router

        Delete a router  # noqa: E501
        """
        pass

    def test_delete_transit_router(self):
        """Test case for delete_transit_router

        Delete a router  # noqa: E501
        """
        pass

    def test_detail_router(self):
        """Test case for detail_router

        Retrieves a single router  # noqa: E501
        """
        pass

    def test_detail_transit_router(self):
        """Test case for detail_transit_router

        Retrieves a single router  # noqa: E501
        """
        pass

    def test_list_routers(self):
        """Test case for list_routers

        List routers  # noqa: E501
        """
        pass

    def test_list_transit_routers(self):
        """Test case for list_transit_routers

        List routers  # noqa: E501
        """
        pass

    def test_patch_router(self):
        """Test case for patch_router

        Update the supplied fields on a router  # noqa: E501
        """
        pass

    def test_patch_transit_router(self):
        """Test case for patch_transit_router

        Update the supplied fields on a router  # noqa: E501
        """
        pass

    def test_update_router(self):
        """Test case for update_router

        Update all fields on a router  # noqa: E501
        """
        pass

    def test_update_transit_router(self):
        """Test case for update_transit_router

        Update all fields on a router  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
