"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.external_jwt_signer_detail import ExternalJwtSignerDetail
globals()['ExternalJwtSignerDetail'] = ExternalJwtSignerDetail
from openziti_edge_management.model.external_jwt_signer_list import ExternalJwtSignerList


class TestExternalJwtSignerList(unittest.TestCase):
    """ExternalJwtSignerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalJwtSignerList(self):
        """Test ExternalJwtSignerList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalJwtSignerList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
