"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.version import Version
globals()['Meta'] = Meta
globals()['Version'] = Version
from openziti_edge_management.model.list_version_envelope import ListVersionEnvelope


class TestListVersionEnvelope(unittest.TestCase):
    """ListVersionEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListVersionEnvelope(self):
        """Test ListVersionEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListVersionEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
