"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.authenticator_list import AuthenticatorList
from openziti_edge_management.model.meta import Meta
globals()['AuthenticatorList'] = AuthenticatorList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_authenticators_envelope import ListAuthenticatorsEnvelope


class TestListAuthenticatorsEnvelope(unittest.TestCase):
    """ListAuthenticatorsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAuthenticatorsEnvelope(self):
        """Test ListAuthenticatorsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAuthenticatorsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
