"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.edge_router_list import EdgeRouterList
from openziti_edge_management.model.meta import Meta
globals()['EdgeRouterList'] = EdgeRouterList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_edge_routers_envelope import ListEdgeRoutersEnvelope


class TestListEdgeRoutersEnvelope(unittest.TestCase):
    """ListEdgeRoutersEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListEdgeRoutersEnvelope(self):
        """Test ListEdgeRoutersEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListEdgeRoutersEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
