"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.session_management_list import SessionManagementList
globals()['Meta'] = Meta
globals()['SessionManagementList'] = SessionManagementList
from openziti_edge_management.model.list_sessions_management_envelope import ListSessionsManagementEnvelope


class TestListSessionsManagementEnvelope(unittest.TestCase):
    """ListSessionsManagementEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSessionsManagementEnvelope(self):
        """Test ListSessionsManagementEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListSessionsManagementEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
