"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_management
from openziti_edge_management.api.identity_api import IdentityApi  # noqa: E501


class TestIdentityApi(unittest.TestCase):
    """IdentityApi unit test stubs"""

    def setUp(self):
        self.api = IdentityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_associate_identitys_service_configs(self):
        """Test case for associate_identitys_service_configs

        Associate service configs for a specific identity  # noqa: E501
        """
        pass

    def test_create_identity(self):
        """Test case for create_identity

        Create an identity resource  # noqa: E501
        """
        pass

    def test_delete_identity(self):
        """Test case for delete_identity

        Delete an identity  # noqa: E501
        """
        pass

    def test_detail_identity(self):
        """Test case for detail_identity

        Retrieves a single identity  # noqa: E501
        """
        pass

    def test_detail_identity_type(self):
        """Test case for detail_identity_type

        Retrieves a identity type  # noqa: E501
        """
        pass

    def test_disable_identity(self):
        """Test case for disable_identity

        Set an identity as disabled  # noqa: E501
        """
        pass

    def test_disassociate_identitys_service_configs(self):
        """Test case for disassociate_identitys_service_configs

        Remove associated service configs from a specific identity  # noqa: E501
        """
        pass

    def test_enable_identity(self):
        """Test case for enable_identity

        Clears all disabled state from an identity  # noqa: E501
        """
        pass

    def test_get_identity_authenticators(self):
        """Test case for get_identity_authenticators

        Retrieve the current authenticators of a specific identity  # noqa: E501
        """
        pass

    def test_get_identity_enrollments(self):
        """Test case for get_identity_enrollments

        Retrieve the current enrollments of a specific identity  # noqa: E501
        """
        pass

    def test_get_identity_failed_service_requests(self):
        """Test case for get_identity_failed_service_requests

        Retrieve a list of the most recent service failure requests due to posture checks  # noqa: E501
        """
        pass

    def test_get_identity_policy_advice(self):
        """Test case for get_identity_policy_advice

        Analyze policies relating the given identity and service  # noqa: E501
        """
        pass

    def test_get_identity_posture_data(self):
        """Test case for get_identity_posture_data

        Retrieve the curent posture data for a specific identity.  # noqa: E501
        """
        pass

    def test_list_identities(self):
        """Test case for list_identities

        List identities  # noqa: E501
        """
        pass

    def test_list_identity_edge_routers(self):
        """Test case for list_identity_edge_routers

        List accessible edge-routers  # noqa: E501
        """
        pass

    def test_list_identity_service_policies(self):
        """Test case for list_identity_service_policies

        List the service policies that affect an identity  # noqa: E501
        """
        pass

    def test_list_identity_services(self):
        """Test case for list_identity_services

        List accessible services  # noqa: E501
        """
        pass

    def test_list_identity_types(self):
        """Test case for list_identity_types

        List available identity types  # noqa: E501
        """
        pass

    def test_list_identitys_edge_router_policies(self):
        """Test case for list_identitys_edge_router_policies

        List the edge router policies that affect an identity  # noqa: E501
        """
        pass

    def test_list_identitys_service_configs(self):
        """Test case for list_identitys_service_configs

        List the service configs associated a specific identity  # noqa: E501
        """
        pass

    def test_patch_identity(self):
        """Test case for patch_identity

        Update the supplied fields on an identity  # noqa: E501
        """
        pass

    def test_remove_identity_mfa(self):
        """Test case for remove_identity_mfa

        Remove MFA from an identitity  # noqa: E501
        """
        pass

    def test_update_identity(self):
        """Test case for update_identity

        Update all fields on an identity  # noqa: E501
        """
        pass

    def test_update_identity_tracing(self):
        """Test case for update_identity_tracing

        Enable/disable data flow tracing for an identity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
