"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.posture_data_endpoint_state import PostureDataEndpointState
from openziti_edge_management.model.posture_data_mfa import PostureDataMfa
from openziti_edge_management.model.sdk_info import SdkInfo
globals()['PostureDataEndpointState'] = PostureDataEndpointState
globals()['PostureDataMfa'] = PostureDataMfa
globals()['SdkInfo'] = SdkInfo
from openziti_edge_management.model.api_session_posture_data import ApiSessionPostureData


class TestApiSessionPostureData(unittest.TestCase):
    """ApiSessionPostureData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiSessionPostureData(self):
        """Test ApiSessionPostureData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiSessionPostureData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
