"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.tags import Tags
globals()['Tags'] = Tags
from openziti_edge_management.model.service_update import ServiceUpdate


class TestServiceUpdate(unittest.TestCase):
    """ServiceUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceUpdate(self):
        """Test ServiceUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
