"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.config_list import ConfigList
from openziti_edge_management.model.meta import Meta
globals()['ConfigList'] = ConfigList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_configs_envelope import ListConfigsEnvelope


class TestListConfigsEnvelope(unittest.TestCase):
    """ListConfigsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListConfigsEnvelope(self):
        """Test ListConfigsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListConfigsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
