"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.posture_data import PostureData
globals()['Meta'] = Meta
globals()['PostureData'] = PostureData
from openziti_edge_management.model.posture_data_envelope import PostureDataEnvelope


class TestPostureDataEnvelope(unittest.TestCase):
    """PostureDataEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureDataEnvelope(self):
        """Test PostureDataEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureDataEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
