"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.posture_check_create import PostureCheckCreate
from openziti_edge_management.model.posture_check_mac_address_create_all_of import PostureCheckMacAddressCreateAllOf
from openziti_edge_management.model.posture_check_type import PostureCheckType
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['PostureCheckCreate'] = PostureCheckCreate
globals()['PostureCheckMacAddressCreateAllOf'] = PostureCheckMacAddressCreateAllOf
globals()['PostureCheckType'] = PostureCheckType
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_mac_address_create import PostureCheckMacAddressCreate


class TestPostureCheckMacAddressCreate(unittest.TestCase):
    """PostureCheckMacAddressCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckMacAddressCreate(self):
        """Test PostureCheckMacAddressCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckMacAddressCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
