"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.current_api_session_detail_all_of import CurrentApiSessionDetailAllOf


class TestCurrentApiSessionDetailAllOf(unittest.TestCase):
    """CurrentApiSessionDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurrentApiSessionDetailAllOf(self):
        """Test CurrentApiSessionDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CurrentApiSessionDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
