"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.sub_tags import SubTags
globals()['SubTags'] = SubTags
from openziti_edge_management.model.tags import Tags


class TestTags(unittest.TestCase):
    """Tags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTags(self):
        """Test Tags"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tags()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
