"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.auth_policy_detail_all_of import AuthPolicyDetailAllOf
from openziti_edge_management.model.auth_policy_primary import AuthPolicyPrimary
from openziti_edge_management.model.auth_policy_secondary import AuthPolicySecondary
from openziti_edge_management.model.base_entity import BaseEntity
from openziti_edge_management.model.links import Links
from openziti_edge_management.model.tags import Tags
globals()['AuthPolicyDetailAllOf'] = AuthPolicyDetailAllOf
globals()['AuthPolicyPrimary'] = AuthPolicyPrimary
globals()['AuthPolicySecondary'] = AuthPolicySecondary
globals()['BaseEntity'] = BaseEntity
globals()['Links'] = Links
globals()['Tags'] = Tags
from openziti_edge_management.model.auth_policy_detail import AuthPolicyDetail


class TestAuthPolicyDetail(unittest.TestCase):
    """AuthPolicyDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthPolicyDetail(self):
        """Test AuthPolicyDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthPolicyDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
