"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.roles import Roles
from openziti_edge_management.model.semantic import Semantic
from openziti_edge_management.model.tags import Tags
globals()['Roles'] = Roles
globals()['Semantic'] = Semantic
globals()['Tags'] = Tags
from openziti_edge_management.model.service_edge_router_policy_update import ServiceEdgeRouterPolicyUpdate


class TestServiceEdgeRouterPolicyUpdate(unittest.TestCase):
    """ServiceEdgeRouterPolicyUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceEdgeRouterPolicyUpdate(self):
        """Test ServiceEdgeRouterPolicyUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceEdgeRouterPolicyUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
