"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.named_roles import NamedRoles
from openziti_edge_management.model.roles import Roles
from openziti_edge_management.model.semantic import Semantic
globals()['NamedRoles'] = NamedRoles
globals()['Roles'] = Roles
globals()['Semantic'] = Semantic
from openziti_edge_management.model.service_edge_router_policy_detail_all_of import ServiceEdgeRouterPolicyDetailAllOf


class TestServiceEdgeRouterPolicyDetailAllOf(unittest.TestCase):
    """ServiceEdgeRouterPolicyDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceEdgeRouterPolicyDetailAllOf(self):
        """Test ServiceEdgeRouterPolicyDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceEdgeRouterPolicyDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
