"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.external_jwt_signer_list import ExternalJwtSignerList
from openziti_edge_management.model.meta import Meta
globals()['ExternalJwtSignerList'] = ExternalJwtSignerList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_external_jwt_signers_envelope import ListExternalJwtSignersEnvelope


class TestListExternalJwtSignersEnvelope(unittest.TestCase):
    """ListExternalJwtSignersEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListExternalJwtSignersEnvelope(self):
        """Test ListExternalJwtSignersEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListExternalJwtSignersEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
