"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_management
from openziti_edge_management.api.auth_policy_api import AuthPolicyApi  # noqa: E501


class TestAuthPolicyApi(unittest.TestCase):
    """AuthPolicyApi unit test stubs"""

    def setUp(self):
        self.api = AuthPolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_auth_policy(self):
        """Test case for create_auth_policy

        Creates an Auth Policy  # noqa: E501
        """
        pass

    def test_delete_auth_policy(self):
        """Test case for delete_auth_policy

        Delete an Auth Policy  # noqa: E501
        """
        pass

    def test_detail_auth_policy(self):
        """Test case for detail_auth_policy

        Retrieves a single Auth Policy  # noqa: E501
        """
        pass

    def test_list_auth_policies(self):
        """Test case for list_auth_policies

        List Auth Policies  # noqa: E501
        """
        pass

    def test_patch_auth_policy(self):
        """Test case for patch_auth_policy

        Update the supplied fields on an Auth Policy  # noqa: E501
        """
        pass

    def test_update_auth_policy(self):
        """Test case for update_auth_policy

        Update all fields on an Auth Policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
