"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.posture_check_type_detail import PostureCheckTypeDetail
globals()['Meta'] = Meta
globals()['PostureCheckTypeDetail'] = PostureCheckTypeDetail
from openziti_edge_management.model.detail_posture_check_type_envelope import DetailPostureCheckTypeEnvelope


class TestDetailPostureCheckTypeEnvelope(unittest.TestCase):
    """DetailPostureCheckTypeEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailPostureCheckTypeEnvelope(self):
        """Test DetailPostureCheckTypeEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailPostureCheckTypeEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
