"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.edge_router_policy_list import EdgeRouterPolicyList
from openziti_edge_management.model.meta import Meta
globals()['EdgeRouterPolicyList'] = EdgeRouterPolicyList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_edge_router_policies_envelope import ListEdgeRouterPoliciesEnvelope


class TestListEdgeRouterPoliciesEnvelope(unittest.TestCase):
    """ListEdgeRouterPoliciesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListEdgeRouterPoliciesEnvelope(self):
        """Test ListEdgeRouterPoliciesEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListEdgeRouterPoliciesEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
