"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.data_integrity_check_detail_list import DataIntegrityCheckDetailList
globals()['DataIntegrityCheckDetailList'] = DataIntegrityCheckDetailList
from openziti_edge_management.model.data_integrity_check_details import DataIntegrityCheckDetails


class TestDataIntegrityCheckDetails(unittest.TestCase):
    """DataIntegrityCheckDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataIntegrityCheckDetails(self):
        """Test DataIntegrityCheckDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataIntegrityCheckDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
