"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.posture_check_mac_address_patch_all_of import PostureCheckMacAddressPatchAllOf
from openziti_edge_management.model.posture_check_patch import PostureCheckPatch
from openziti_edge_management.model.posture_check_type import PostureCheckType
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['PostureCheckMacAddressPatchAllOf'] = PostureCheckMacAddressPatchAllOf
globals()['PostureCheckPatch'] = PostureCheckPatch
globals()['PostureCheckType'] = PostureCheckType
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_mac_address_patch import PostureCheckMacAddressPatch


class TestPostureCheckMacAddressPatch(unittest.TestCase):
    """PostureCheckMacAddressPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckMacAddressPatch(self):
        """Test PostureCheckMacAddressPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckMacAddressPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
