"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_management
from openziti_edge_management.api.service_edge_router_policy_api import ServiceEdgeRouterPolicyApi  # noqa: E501


class TestServiceEdgeRouterPolicyApi(unittest.TestCase):
    """ServiceEdgeRouterPolicyApi unit test stubs"""

    def setUp(self):
        self.api = ServiceEdgeRouterPolicyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_service_edge_router_policy(self):
        """Test case for create_service_edge_router_policy

        Create a service edge router policy resource  # noqa: E501
        """
        pass

    def test_delete_service_edge_router_policy(self):
        """Test case for delete_service_edge_router_policy

        Delete a service edge policy  # noqa: E501
        """
        pass

    def test_detail_service_edge_router_policy(self):
        """Test case for detail_service_edge_router_policy

        Retrieves a single service edge policy  # noqa: E501
        """
        pass

    def test_list_service_edge_router_policies(self):
        """Test case for list_service_edge_router_policies

        List service edge router policies  # noqa: E501
        """
        pass

    def test_list_service_edge_router_policy_edge_routers(self):
        """Test case for list_service_edge_router_policy_edge_routers

        List the edge routers that a service edge router policy applies to  # noqa: E501
        """
        pass

    def test_list_service_edge_router_policy_services(self):
        """Test case for list_service_edge_router_policy_services

        List the services that a service edge router policy applies to  # noqa: E501
        """
        pass

    def test_patch_service_edge_router_policy(self):
        """Test case for patch_service_edge_router_policy

        Update the supplied fields on a service edge policy  # noqa: E501
        """
        pass

    def test_update_service_edge_router_policy(self):
        """Test case for update_service_edge_router_policy

        Update all fields on a service edge policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
