"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.service_edge_router_policy_detail import ServiceEdgeRouterPolicyDetail
globals()['ServiceEdgeRouterPolicyDetail'] = ServiceEdgeRouterPolicyDetail
from openziti_edge_management.model.service_edge_router_policy_list import ServiceEdgeRouterPolicyList


class TestServiceEdgeRouterPolicyList(unittest.TestCase):
    """ServiceEdgeRouterPolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceEdgeRouterPolicyList(self):
        """Test ServiceEdgeRouterPolicyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceEdgeRouterPolicyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
