"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.identity_enrollments_ott import IdentityEnrollmentsOtt
from openziti_edge_management.model.identity_enrollments_ottca import IdentityEnrollmentsOttca
globals()['IdentityEnrollmentsOtt'] = IdentityEnrollmentsOtt
globals()['IdentityEnrollmentsOttca'] = IdentityEnrollmentsOttca
from openziti_edge_management.model.identity_enrollments import IdentityEnrollments


class TestIdentityEnrollments(unittest.TestCase):
    """IdentityEnrollments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityEnrollments(self):
        """Test IdentityEnrollments"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentityEnrollments()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
