"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.config_detail import ConfigDetail
from openziti_edge_management.model.meta import Meta
globals()['ConfigDetail'] = ConfigDetail
globals()['Meta'] = Meta
from openziti_edge_management.model.detail_config_envelope import DetailConfigEnvelope


class TestDetailConfigEnvelope(unittest.TestCase):
    """DetailConfigEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailConfigEnvelope(self):
        """Test DetailConfigEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailConfigEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
