"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.tags import Tags
globals()['Tags'] = Tags
from openziti_edge_management.model.external_jwt_signer_update import ExternalJwtSignerUpdate


class TestExternalJwtSignerUpdate(unittest.TestCase):
    """ExternalJwtSignerUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalJwtSignerUpdate(self):
        """Test ExternalJwtSignerUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalJwtSignerUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
