"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.service_config_detail import ServiceConfigDetail
globals()['ServiceConfigDetail'] = ServiceConfigDetail
from openziti_edge_management.model.service_config_list import ServiceConfigList


class TestServiceConfigList(unittest.TestCase):
    """ServiceConfigList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceConfigList(self):
        """Test ServiceConfigList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceConfigList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
