"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.authenticator_patch_with_current_all_of import AuthenticatorPatchWithCurrentAllOf
from openziti_edge_management.model.authenticator_update import AuthenticatorUpdate
from openziti_edge_management.model.password import Password
from openziti_edge_management.model.tags import Tags
from openziti_edge_management.model.username import Username
globals()['AuthenticatorPatchWithCurrentAllOf'] = AuthenticatorPatchWithCurrentAllOf
globals()['AuthenticatorUpdate'] = AuthenticatorUpdate
globals()['Password'] = Password
globals()['Tags'] = Tags
globals()['Username'] = Username
from openziti_edge_management.model.authenticator_update_with_current import AuthenticatorUpdateWithCurrent


class TestAuthenticatorUpdateWithCurrent(unittest.TestCase):
    """AuthenticatorUpdateWithCurrent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticatorUpdateWithCurrent(self):
        """Test AuthenticatorUpdateWithCurrent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthenticatorUpdateWithCurrent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
