"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.ca_list import CaList
from openziti_edge_management.model.meta import Meta
globals()['CaList'] = CaList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_cas_envelope import ListCasEnvelope


class TestListCasEnvelope(unittest.TestCase):
    """ListCasEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListCasEnvelope(self):
        """Test ListCasEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListCasEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
