"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.operating_system import OperatingSystem
from openziti_edge_management.model.posture_check_operating_system_create_all_of import PostureCheckOperatingSystemCreateAllOf
from openziti_edge_management.model.posture_check_type import PostureCheckType
from openziti_edge_management.model.posture_check_update import PostureCheckUpdate
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['OperatingSystem'] = OperatingSystem
globals()['PostureCheckOperatingSystemCreateAllOf'] = PostureCheckOperatingSystemCreateAllOf
globals()['PostureCheckType'] = PostureCheckType
globals()['PostureCheckUpdate'] = PostureCheckUpdate
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_operating_system_update import PostureCheckOperatingSystemUpdate


class TestPostureCheckOperatingSystemUpdate(unittest.TestCase):
    """PostureCheckOperatingSystemUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckOperatingSystemUpdate(self):
        """Test PostureCheckOperatingSystemUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckOperatingSystemUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
