"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.entity_ref import EntityRef
globals()['EntityRef'] = EntityRef
from openziti_edge_management.model.identity_enrollments_ottca import IdentityEnrollmentsOttca


class TestIdentityEnrollmentsOttca(unittest.TestCase):
    """IdentityEnrollmentsOttca unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityEnrollmentsOttca(self):
        """Test IdentityEnrollmentsOttca"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentityEnrollmentsOttca()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
