"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.router_detail import RouterDetail
globals()['Meta'] = Meta
globals()['RouterDetail'] = RouterDetail
from openziti_edge_management.model.detail_router_envelope import DetailRouterEnvelope


class TestDetailRouterEnvelope(unittest.TestCase):
    """DetailRouterEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailRouterEnvelope(self):
        """Test DetailRouterEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailRouterEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
