"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.list_summary_counts import ListSummaryCounts
from openziti_edge_management.model.meta import Meta
globals()['ListSummaryCounts'] = ListSummaryCounts
globals()['Meta'] = Meta
from openziti_edge_management.model.list_summary_counts_envelope import ListSummaryCountsEnvelope


class TestListSummaryCountsEnvelope(unittest.TestCase):
    """ListSummaryCountsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSummaryCountsEnvelope(self):
        """Test ListSummaryCountsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListSummaryCountsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
