"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.dial_bind_array import DialBindArray
from openziti_edge_management.model.posture_queries import PostureQueries
globals()['Attributes'] = Attributes
globals()['DialBindArray'] = DialBindArray
globals()['PostureQueries'] = PostureQueries
from openziti_edge_management.model.service_detail_all_of import ServiceDetailAllOf


class TestServiceDetailAllOf(unittest.TestCase):
    """ServiceDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceDetailAllOf(self):
        """Test ServiceDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
