"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.posture_check_detail import PostureCheckDetail
globals()['Meta'] = Meta
globals()['PostureCheckDetail'] = PostureCheckDetail
from openziti_edge_management.model.list_posture_check_envelope import ListPostureCheckEnvelope


class TestListPostureCheckEnvelope(unittest.TestCase):
    """ListPostureCheckEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPostureCheckEnvelope(self):
        """Test ListPostureCheckEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListPostureCheckEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
