"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.detail_mfa_recovery_codes import DetailMfaRecoveryCodes
from openziti_edge_management.model.meta import Meta
globals()['DetailMfaRecoveryCodes'] = DetailMfaRecoveryCodes
globals()['Meta'] = Meta
from openziti_edge_management.model.detail_mfa_recovery_codes_envelope import DetailMfaRecoveryCodesEnvelope


class TestDetailMfaRecoveryCodesEnvelope(unittest.TestCase):
    """DetailMfaRecoveryCodesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailMfaRecoveryCodesEnvelope(self):
        """Test DetailMfaRecoveryCodesEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailMfaRecoveryCodesEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
