"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.links import Links
from openziti_edge_management.model.posture_check_detail import PostureCheckDetail
from openziti_edge_management.model.posture_check_process_multi_create_all_of import PostureCheckProcessMultiCreateAllOf
from openziti_edge_management.model.process_multi import ProcessMulti
from openziti_edge_management.model.semantic import Semantic
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['Links'] = Links
globals()['PostureCheckDetail'] = PostureCheckDetail
globals()['PostureCheckProcessMultiCreateAllOf'] = PostureCheckProcessMultiCreateAllOf
globals()['ProcessMulti'] = ProcessMulti
globals()['Semantic'] = Semantic
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_process_multi_detail import PostureCheckProcessMultiDetail


class TestPostureCheckProcessMultiDetail(unittest.TestCase):
    """PostureCheckProcessMultiDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckProcessMultiDetail(self):
        """Test PostureCheckProcessMultiDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckProcessMultiDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
