"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
globals()['Meta'] = Meta
from openziti_edge_management.model.detail_spec_body_envelope import DetailSpecBodyEnvelope


class TestDetailSpecBodyEnvelope(unittest.TestCase):
    """DetailSpecBodyEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailSpecBodyEnvelope(self):
        """Test DetailSpecBodyEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailSpecBodyEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
