"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.spec_detail import SpecDetail
globals()['Meta'] = Meta
globals()['SpecDetail'] = SpecDetail
from openziti_edge_management.model.detail_spec_envelope import DetailSpecEnvelope


class TestDetailSpecEnvelope(unittest.TestCase):
    """DetailSpecEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailSpecEnvelope(self):
        """Test DetailSpecEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailSpecEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
