"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.posture_check_mac_address_create_all_of import PostureCheckMacAddressCreateAllOf
from openziti_edge_management.model.posture_check_type import PostureCheckType
from openziti_edge_management.model.posture_check_update import PostureCheckUpdate
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['PostureCheckMacAddressCreateAllOf'] = PostureCheckMacAddressCreateAllOf
globals()['PostureCheckType'] = PostureCheckType
globals()['PostureCheckUpdate'] = PostureCheckUpdate
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_mac_address_update import PostureCheckMacAddressUpdate


class TestPostureCheckMacAddressUpdate(unittest.TestCase):
    """PostureCheckMacAddressUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckMacAddressUpdate(self):
        """Test PostureCheckMacAddressUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckMacAddressUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
