"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.dial_bind import DialBind
from openziti_edge_management.model.entity_ref import EntityRef
from openziti_edge_management.model.session_edge_router import SessionEdgeRouter
globals()['DialBind'] = DialBind
globals()['EntityRef'] = EntityRef
globals()['SessionEdgeRouter'] = SessionEdgeRouter
from openziti_edge_management.model.session_detail_all_of import SessionDetailAllOf


class TestSessionDetailAllOf(unittest.TestCase):
    """SessionDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionDetailAllOf(self):
        """Test SessionDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
