"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.posture_check_patch import PostureCheckPatch
from openziti_edge_management.model.posture_check_process_patch_all_of import PostureCheckProcessPatchAllOf
from openziti_edge_management.model.posture_check_type import PostureCheckType
from openziti_edge_management.model.process import Process
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['PostureCheckPatch'] = PostureCheckPatch
globals()['PostureCheckProcessPatchAllOf'] = PostureCheckProcessPatchAllOf
globals()['PostureCheckType'] = PostureCheckType
globals()['Process'] = Process
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_process_patch import PostureCheckProcessPatch


class TestPostureCheckProcessPatch(unittest.TestCase):
    """PostureCheckProcessPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckProcessPatch(self):
        """Test PostureCheckProcessPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckProcessPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
