"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.entity_ref import EntityRef
from openziti_edge_management.model.links import Links
from openziti_edge_management.model.router_entity_ref_all_of import RouterEntityRefAllOf
globals()['EntityRef'] = EntityRef
globals()['Links'] = Links
globals()['RouterEntityRefAllOf'] = RouterEntityRefAllOf
from openziti_edge_management.model.router_entity_ref import RouterEntityRef


class TestRouterEntityRef(unittest.TestCase):
    """RouterEntityRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRouterEntityRef(self):
        """Test RouterEntityRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RouterEntityRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
