"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.posture_check_failure import PostureCheckFailure
from openziti_edge_management.model.posture_check_failure_process_actual import PostureCheckFailureProcessActual
from openziti_edge_management.model.posture_check_failure_process_all_of import PostureCheckFailureProcessAllOf
from openziti_edge_management.model.process import Process
globals()['PostureCheckFailure'] = PostureCheckFailure
globals()['PostureCheckFailureProcessActual'] = PostureCheckFailureProcessActual
globals()['PostureCheckFailureProcessAllOf'] = PostureCheckFailureProcessAllOf
globals()['Process'] = Process
from openziti_edge_management.model.posture_check_failure_process import PostureCheckFailureProcess


class TestPostureCheckFailureProcess(unittest.TestCase):
    """PostureCheckFailureProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckFailureProcess(self):
        """Test PostureCheckFailureProcess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckFailureProcess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
