"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.posture_check_create import PostureCheckCreate
from openziti_edge_management.model.posture_check_mfa_properties import PostureCheckMfaProperties
from openziti_edge_management.model.posture_check_type import PostureCheckType
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['PostureCheckCreate'] = PostureCheckCreate
globals()['PostureCheckMfaProperties'] = PostureCheckMfaProperties
globals()['PostureCheckType'] = PostureCheckType
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_mfa_create import PostureCheckMfaCreate


class TestPostureCheckMfaCreate(unittest.TestCase):
    """PostureCheckMfaCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckMfaCreate(self):
        """Test PostureCheckMfaCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckMfaCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
