"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.mfa_formats import MfaFormats
from openziti_edge_management.model.mfa_providers import MfaProviders
globals()['MfaFormats'] = MfaFormats
globals()['MfaProviders'] = MfaProviders
from openziti_edge_management.model.auth_query_detail import AuthQueryDetail


class TestAuthQueryDetail(unittest.TestCase):
    """AuthQueryDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthQueryDetail(self):
        """Test AuthQueryDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthQueryDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
