"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.identity_type_detail import IdentityTypeDetail
globals()['IdentityTypeDetail'] = IdentityTypeDetail
from openziti_edge_management.model.identity_type_list import IdentityTypeList


class TestIdentityTypeList(unittest.TestCase):
    """IdentityTypeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityTypeList(self):
        """Test IdentityTypeList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentityTypeList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
