"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.named_roles import NamedRoles
from openziti_edge_management.model.roles import Roles
from openziti_edge_management.model.semantic import Semantic
globals()['NamedRoles'] = NamedRoles
globals()['Roles'] = Roles
globals()['Semantic'] = Semantic
from openziti_edge_management.model.edge_router_policy_detail_all_of import EdgeRouterPolicyDetailAllOf


class TestEdgeRouterPolicyDetailAllOf(unittest.TestCase):
    """EdgeRouterPolicyDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdgeRouterPolicyDetailAllOf(self):
        """Test EdgeRouterPolicyDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EdgeRouterPolicyDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
