"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.base_entity import BaseEntity
from openziti_edge_management.model.links import Links
from openziti_edge_management.model.operating_system import OperatingSystem
from openziti_edge_management.model.posture_check_type_detail_all_of import PostureCheckTypeDetailAllOf
from openziti_edge_management.model.tags import Tags
globals()['BaseEntity'] = BaseEntity
globals()['Links'] = Links
globals()['OperatingSystem'] = OperatingSystem
globals()['PostureCheckTypeDetailAllOf'] = PostureCheckTypeDetailAllOf
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_type_detail import PostureCheckTypeDetail


class TestPostureCheckTypeDetail(unittest.TestCase):
    """PostureCheckTypeDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckTypeDetail(self):
        """Test PostureCheckTypeDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckTypeDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
