"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.posture_check_domain_update import PostureCheckDomainUpdate
from openziti_edge_management.model.posture_check_mac_address_update import PostureCheckMacAddressUpdate
from openziti_edge_management.model.posture_check_mfa_update import PostureCheckMfaUpdate
from openziti_edge_management.model.posture_check_operating_system_update import PostureCheckOperatingSystemUpdate
from openziti_edge_management.model.posture_check_process_multi_update import PostureCheckProcessMultiUpdate
from openziti_edge_management.model.posture_check_process_update import PostureCheckProcessUpdate
from openziti_edge_management.model.posture_check_type import PostureCheckType
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['PostureCheckDomainUpdate'] = PostureCheckDomainUpdate
globals()['PostureCheckMacAddressUpdate'] = PostureCheckMacAddressUpdate
globals()['PostureCheckMfaUpdate'] = PostureCheckMfaUpdate
globals()['PostureCheckOperatingSystemUpdate'] = PostureCheckOperatingSystemUpdate
globals()['PostureCheckProcessMultiUpdate'] = PostureCheckProcessMultiUpdate
globals()['PostureCheckProcessUpdate'] = PostureCheckProcessUpdate
globals()['PostureCheckType'] = PostureCheckType
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_update import PostureCheckUpdate


class TestPostureCheckUpdate(unittest.TestCase):
    """PostureCheckUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckUpdate(self):
        """Test PostureCheckUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
