"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.external_id_claim import ExternalIdClaim
from openziti_edge_management.model.roles import Roles
globals()['ExternalIdClaim'] = ExternalIdClaim
globals()['Roles'] = Roles
from openziti_edge_management.model.ca_detail_all_of import CaDetailAllOf


class TestCaDetailAllOf(unittest.TestCase):
    """CaDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaDetailAllOf(self):
        """Test CaDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
