"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.service_config_list import ServiceConfigList
globals()['Meta'] = Meta
globals()['ServiceConfigList'] = ServiceConfigList
from openziti_edge_management.model.list_service_configs_envelope import ListServiceConfigsEnvelope


class TestListServiceConfigsEnvelope(unittest.TestCase):
    """ListServiceConfigsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListServiceConfigsEnvelope(self):
        """Test ListServiceConfigsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListServiceConfigsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
