"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.auth_policy_detail import AuthPolicyDetail
globals()['AuthPolicyDetail'] = AuthPolicyDetail
from openziti_edge_management.model.auth_policy_list import AuthPolicyList


class TestAuthPolicyList(unittest.TestCase):
    """AuthPolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthPolicyList(self):
        """Test AuthPolicyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthPolicyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
