"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.sdk_info import SdkInfo


class TestSdkInfo(unittest.TestCase):
    """SdkInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSdkInfo(self):
        """Test SdkInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SdkInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
