"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.api_session_list import ApiSessionList
from openziti_edge_management.model.meta import Meta
globals()['ApiSessionList'] = ApiSessionList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_api_sessions_envelope import ListApiSessionsEnvelope


class TestListApiSessionsEnvelope(unittest.TestCase):
    """ListApiSessionsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListApiSessionsEnvelope(self):
        """Test ListApiSessionsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListApiSessionsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
