"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.tags import Tags
globals()['Tags'] = Tags
from openziti_edge_management.model.external_jwt_signer_create import ExternalJwtSignerCreate


class TestExternalJwtSignerCreate(unittest.TestCase):
    """ExternalJwtSignerCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalJwtSignerCreate(self):
        """Test ExternalJwtSignerCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalJwtSignerCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
