"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.identity_create_enrollment import IdentityCreateEnrollment


class TestIdentityCreateEnrollment(unittest.TestCase):
    """IdentityCreateEnrollment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityCreateEnrollment(self):
        """Test IdentityCreateEnrollment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentityCreateEnrollment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
