"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.terminator_list import TerminatorList
globals()['Meta'] = Meta
globals()['TerminatorList'] = TerminatorList
from openziti_edge_management.model.list_terminators_envelope import ListTerminatorsEnvelope


class TestListTerminatorsEnvelope(unittest.TestCase):
    """ListTerminatorsEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListTerminatorsEnvelope(self):
        """Test ListTerminatorsEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListTerminatorsEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
