"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.posture_check_process_create_all_of import PostureCheckProcessCreateAllOf
from openziti_edge_management.model.posture_check_type import PostureCheckType
from openziti_edge_management.model.posture_check_update import PostureCheckUpdate
from openziti_edge_management.model.process import Process
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['PostureCheckProcessCreateAllOf'] = PostureCheckProcessCreateAllOf
globals()['PostureCheckType'] = PostureCheckType
globals()['PostureCheckUpdate'] = PostureCheckUpdate
globals()['Process'] = Process
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_process_update import PostureCheckProcessUpdate


class TestPostureCheckProcessUpdate(unittest.TestCase):
    """PostureCheckProcessUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckProcessUpdate(self):
        """Test PostureCheckProcessUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckProcessUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
