"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.links import Links
globals()['Links'] = Links
from openziti_edge_management.model.entity_ref import EntityRef


class TestEntityRef(unittest.TestCase):
    """EntityRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityRef(self):
        """Test EntityRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntityRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
