"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.password_nullable import PasswordNullable


class TestPasswordNullable(unittest.TestCase):
    """PasswordNullable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPasswordNullable(self):
        """Test PasswordNullable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PasswordNullable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
