"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_management
from openziti_edge_management.api.database_api import DatabaseApi  # noqa: E501


class TestDatabaseApi(unittest.TestCase):
    """DatabaseApi unit test stubs"""

    def setUp(self):
        self.api = DatabaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_data_integrity(self):
        """Test case for check_data_integrity

        Starts a data integrity scan on the datastore  # noqa: E501
        """
        pass

    def test_create_database_snapshot(self):
        """Test case for create_database_snapshot

        Create a new database snapshot  # noqa: E501
        """
        pass

    def test_data_integrity_results(self):
        """Test case for data_integrity_results

        Returns any results found from in-progress integrity checks  # noqa: E501
        """
        pass

    def test_fix_data_integrity(self):
        """Test case for fix_data_integrity

        Runs a data integrity scan on the datastore, attempts to fix any issues it can and returns any found issues  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
