"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.posture_check_failure import PostureCheckFailure
from openziti_edge_management.model.posture_check_failure_mfa_all_of import PostureCheckFailureMfaAllOf
from openziti_edge_management.model.posture_checks_failure_mfa_criteria import PostureChecksFailureMfaCriteria
from openziti_edge_management.model.posture_checks_failure_mfa_values import PostureChecksFailureMfaValues
globals()['PostureCheckFailure'] = PostureCheckFailure
globals()['PostureCheckFailureMfaAllOf'] = PostureCheckFailureMfaAllOf
globals()['PostureChecksFailureMfaCriteria'] = PostureChecksFailureMfaCriteria
globals()['PostureChecksFailureMfaValues'] = PostureChecksFailureMfaValues
from openziti_edge_management.model.posture_check_failure_mfa import PostureCheckFailureMfa


class TestPostureCheckFailureMfa(unittest.TestCase):
    """PostureCheckFailureMfa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckFailureMfa(self):
        """Test PostureCheckFailureMfa"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckFailureMfa()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
