"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.operating_system import OperatingSystem
globals()['OperatingSystem'] = OperatingSystem
from openziti_edge_management.model.posture_check_operating_system_detail_all_of import PostureCheckOperatingSystemDetailAllOf


class TestPostureCheckOperatingSystemDetailAllOf(unittest.TestCase):
    """PostureCheckOperatingSystemDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckOperatingSystemDetailAllOf(self):
        """Test PostureCheckOperatingSystemDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckOperatingSystemDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
