"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.edge_router_policy_detail import EdgeRouterPolicyDetail
globals()['EdgeRouterPolicyDetail'] = EdgeRouterPolicyDetail
from openziti_edge_management.model.edge_router_policy_list import EdgeRouterPolicyList


class TestEdgeRouterPolicyList(unittest.TestCase):
    """EdgeRouterPolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdgeRouterPolicyList(self):
        """Test EdgeRouterPolicyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EdgeRouterPolicyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
