"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.pagination import Pagination
globals()['Pagination'] = Pagination
from openziti_edge_management.model.meta import Meta


class TestMeta(unittest.TestCase):
    """Meta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeta(self):
        """Test Meta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Meta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
