"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.posture_check_failure import PostureCheckFailure
globals()['PostureCheckFailure'] = PostureCheckFailure
from openziti_edge_management.model.policy_failure import PolicyFailure


class TestPolicyFailure(unittest.TestCase):
    """PolicyFailure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyFailure(self):
        """Test PolicyFailure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PolicyFailure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
