"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.identity_type_list import IdentityTypeList
from openziti_edge_management.model.meta import Meta
globals()['IdentityTypeList'] = IdentityTypeList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_identity_types_envelope import ListIdentityTypesEnvelope


class TestListIdentityTypesEnvelope(unittest.TestCase):
    """ListIdentityTypesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListIdentityTypesEnvelope(self):
        """Test ListIdentityTypesEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListIdentityTypesEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
