"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.entity_ref import EntityRef
globals()['EntityRef'] = EntityRef
from openziti_edge_management.model.session_management_detail_all_of import SessionManagementDetailAllOf


class TestSessionManagementDetailAllOf(unittest.TestCase):
    """SessionManagementDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionManagementDetailAllOf(self):
        """Test SessionManagementDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionManagementDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
