"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.entity_ref import EntityRef
from openziti_edge_management.model.terminator_cost import TerminatorCost
from openziti_edge_management.model.terminator_precedence import TerminatorPrecedence
globals()['EntityRef'] = EntityRef
globals()['TerminatorCost'] = TerminatorCost
globals()['TerminatorPrecedence'] = TerminatorPrecedence
from openziti_edge_management.model.terminator_detail_all_of import TerminatorDetailAllOf


class TestTerminatorDetailAllOf(unittest.TestCase):
    """TerminatorDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTerminatorDetailAllOf(self):
        """Test TerminatorDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TerminatorDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
