"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.auth_query_detail import AuthQueryDetail
globals()['AuthQueryDetail'] = AuthQueryDetail
from openziti_edge_management.model.auth_query_list import AuthQueryList


class TestAuthQueryList(unittest.TestCase):
    """AuthQueryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthQueryList(self):
        """Test AuthQueryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthQueryList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
