"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.links import Links
from openziti_edge_management.model.operating_system import OperatingSystem
from openziti_edge_management.model.posture_check_detail import PostureCheckDetail
from openziti_edge_management.model.posture_check_operating_system_detail_all_of import PostureCheckOperatingSystemDetailAllOf
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['Links'] = Links
globals()['OperatingSystem'] = OperatingSystem
globals()['PostureCheckDetail'] = PostureCheckDetail
globals()['PostureCheckOperatingSystemDetailAllOf'] = PostureCheckOperatingSystemDetailAllOf
globals()['Tags'] = Tags
from openziti_edge_management.model.posture_check_operating_system_detail import PostureCheckOperatingSystemDetail


class TestPostureCheckOperatingSystemDetail(unittest.TestCase):
    """PostureCheckOperatingSystemDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckOperatingSystemDetail(self):
        """Test PostureCheckOperatingSystemDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckOperatingSystemDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
