"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.auth_policy_primary_patch import AuthPolicyPrimaryPatch
from openziti_edge_management.model.auth_policy_secondary_patch import AuthPolicySecondaryPatch
from openziti_edge_management.model.tags import Tags
globals()['AuthPolicyPrimaryPatch'] = AuthPolicyPrimaryPatch
globals()['AuthPolicySecondaryPatch'] = AuthPolicySecondaryPatch
globals()['Tags'] = Tags
from openziti_edge_management.model.auth_policy_patch import AuthPolicyPatch


class TestAuthPolicyPatch(unittest.TestCase):
    """AuthPolicyPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthPolicyPatch(self):
        """Test AuthPolicyPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthPolicyPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
