"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.external_jwt_signer_detail import ExternalJwtSignerDetail
from openziti_edge_management.model.meta import Meta
globals()['ExternalJwtSignerDetail'] = ExternalJwtSignerDetail
globals()['Meta'] = Meta
from openziti_edge_management.model.detail_external_jwt_signer_envelope import DetailExternalJwtSignerEnvelope


class TestDetailExternalJwtSignerEnvelope(unittest.TestCase):
    """DetailExternalJwtSignerEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailExternalJwtSignerEnvelope(self):
        """Test DetailExternalJwtSignerEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailExternalJwtSignerEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
