"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.auth_query_list import AuthQueryList
from openziti_edge_management.model.entity_ref import EntityRef
globals()['AuthQueryList'] = AuthQueryList
globals()['EntityRef'] = EntityRef
from openziti_edge_management.model.api_session_detail_all_of import ApiSessionDetailAllOf


class TestApiSessionDetailAllOf(unittest.TestCase):
    """ApiSessionDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiSessionDetailAllOf(self):
        """Test ApiSessionDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiSessionDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
