"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.attributes import Attributes
from openziti_edge_management.model.tags import Tags
globals()['Attributes'] = Attributes
globals()['Tags'] = Tags
from openziti_edge_management.model.edge_router_patch import EdgeRouterPatch


class TestEdgeRouterPatch(unittest.TestCase):
    """EdgeRouterPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdgeRouterPatch(self):
        """Test EdgeRouterPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EdgeRouterPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
