"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.posture_check_failure import PostureCheckFailure
from openziti_edge_management.model.posture_check_failure_mac_address_all_of import PostureCheckFailureMacAddressAllOf
globals()['PostureCheckFailure'] = PostureCheckFailure
globals()['PostureCheckFailureMacAddressAllOf'] = PostureCheckFailureMacAddressAllOf
from openziti_edge_management.model.posture_check_failure_mac_address import PostureCheckFailureMacAddress


class TestPostureCheckFailureMacAddress(unittest.TestCase):
    """PostureCheckFailureMacAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckFailureMacAddress(self):
        """Test PostureCheckFailureMacAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckFailureMacAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
