"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_management
from openziti_edge_management.api.tracing_api import TracingApi  # noqa: E501


class TestTracingApi(unittest.TestCase):
    """TracingApi unit test stubs"""

    def setUp(self):
        self.api = TracingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_identity_tracing(self):
        """Test case for update_identity_tracing

        Enable/disable data flow tracing for an identity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
