"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.trace_detail import TraceDetail
globals()['Meta'] = Meta
globals()['TraceDetail'] = TraceDetail
from openziti_edge_management.model.trace_detail_envelope import TraceDetailEnvelope


class TestTraceDetailEnvelope(unittest.TestCase):
    """TraceDetailEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTraceDetailEnvelope(self):
        """Test TraceDetailEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TraceDetailEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
