"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.posture_data_base import PostureDataBase
from openziti_edge_management.model.posture_data_process_all_of import PostureDataProcessAllOf
globals()['PostureDataBase'] = PostureDataBase
globals()['PostureDataProcessAllOf'] = PostureDataProcessAllOf
from openziti_edge_management.model.posture_data_process import PostureDataProcess


class TestPostureDataProcess(unittest.TestCase):
    """PostureDataProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureDataProcess(self):
        """Test PostureDataProcess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureDataProcess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
