"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import openziti_edge_management
from openziti_edge_management.api.api_session_api import APISessionApi  # noqa: E501


class TestAPISessionApi(unittest.TestCase):
    """APISessionApi unit test stubs"""

    def setUp(self):
        self.api = APISessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_api_sessions(self):
        """Test case for delete_api_sessions

        Deletes an API Sessions  # noqa: E501
        """
        pass

    def test_detail_api_sessions(self):
        """Test case for detail_api_sessions

        Retrieves a single API Session  # noqa: E501
        """
        pass

    def test_list_api_sessions(self):
        """Test case for list_api_sessions

        List active API sessions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
