"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.external_id_claim import ExternalIdClaim
from openziti_edge_management.model.roles import Roles
from openziti_edge_management.model.tags import Tags
globals()['ExternalIdClaim'] = ExternalIdClaim
globals()['Roles'] = Roles
globals()['Tags'] = Tags
from openziti_edge_management.model.ca_create import CaCreate


class TestCaCreate(unittest.TestCase):
    """CaCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCaCreate(self):
        """Test CaCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CaCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
