"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.config_type_detail import ConfigTypeDetail
globals()['ConfigTypeDetail'] = ConfigTypeDetail
from openziti_edge_management.model.config_type_list import ConfigTypeList


class TestConfigTypeList(unittest.TestCase):
    """ConfigTypeList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigTypeList(self):
        """Test ConfigTypeList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfigTypeList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
