"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.auth_policy_primary_cert_patch import AuthPolicyPrimaryCertPatch
from openziti_edge_management.model.auth_policy_primary_ext_jwt_patch import AuthPolicyPrimaryExtJwtPatch
from openziti_edge_management.model.auth_policy_primary_updb_patch import AuthPolicyPrimaryUpdbPatch
globals()['AuthPolicyPrimaryCertPatch'] = AuthPolicyPrimaryCertPatch
globals()['AuthPolicyPrimaryExtJwtPatch'] = AuthPolicyPrimaryExtJwtPatch
globals()['AuthPolicyPrimaryUpdbPatch'] = AuthPolicyPrimaryUpdbPatch
from openziti_edge_management.model.auth_policy_primary_patch import AuthPolicyPrimaryPatch


class TestAuthPolicyPrimaryPatch(unittest.TestCase):
    """AuthPolicyPrimaryPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthPolicyPrimaryPatch(self):
        """Test AuthPolicyPrimaryPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthPolicyPrimaryPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
