"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.auth_policy_primary_updb_patch import AuthPolicyPrimaryUpdbPatch


class TestAuthPolicyPrimaryUpdbPatch(unittest.TestCase):
    """AuthPolicyPrimaryUpdbPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthPolicyPrimaryUpdbPatch(self):
        """Test AuthPolicyPrimaryUpdbPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthPolicyPrimaryUpdbPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
