"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.posture_check_failure_process_actual import PostureCheckFailureProcessActual
from openziti_edge_management.model.process_multi import ProcessMulti
from openziti_edge_management.model.semantic import Semantic
globals()['PostureCheckFailureProcessActual'] = PostureCheckFailureProcessActual
globals()['ProcessMulti'] = ProcessMulti
globals()['Semantic'] = Semantic
from openziti_edge_management.model.posture_check_failure_process_multi_all_of import PostureCheckFailureProcessMultiAllOf


class TestPostureCheckFailureProcessMultiAllOf(unittest.TestCase):
    """PostureCheckFailureProcessMultiAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostureCheckFailureProcessMultiAllOf(self):
        """Test PostureCheckFailureProcessMultiAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostureCheckFailureProcessMultiAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
