"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.meta import Meta
from openziti_edge_management.model.service_policy_list import ServicePolicyList
globals()['Meta'] = Meta
globals()['ServicePolicyList'] = ServicePolicyList
from openziti_edge_management.model.list_service_policies_envelope import ListServicePoliciesEnvelope


class TestListServicePoliciesEnvelope(unittest.TestCase):
    """ListServicePoliciesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListServicePoliciesEnvelope(self):
        """Test ListServicePoliciesEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListServicePoliciesEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
