"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.identity_detail import IdentityDetail
from openziti_edge_management.model.meta import Meta
globals()['IdentityDetail'] = IdentityDetail
globals()['Meta'] = Meta
from openziti_edge_management.model.detail_identity_envelope import DetailIdentityEnvelope


class TestDetailIdentityEnvelope(unittest.TestCase):
    """DetailIdentityEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailIdentityEnvelope(self):
        """Test DetailIdentityEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailIdentityEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
