"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.config_type_list import ConfigTypeList
from openziti_edge_management.model.meta import Meta
globals()['ConfigTypeList'] = ConfigTypeList
globals()['Meta'] = Meta
from openziti_edge_management.model.list_config_types_envelope import ListConfigTypesEnvelope


class TestListConfigTypesEnvelope(unittest.TestCase):
    """ListConfigTypesEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListConfigTypesEnvelope(self):
        """Test ListConfigTypesEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListConfigTypesEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
