"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.links import Links
from openziti_edge_management.model.tags import Tags
globals()['Links'] = Links
globals()['Tags'] = Tags
from openziti_edge_management.model.base_entity import BaseEntity


class TestBaseEntity(unittest.TestCase):
    """BaseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseEntity(self):
        """Test BaseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
