"""
    Ziti Edge Management

    OpenZiti Edge Management API  # noqa: E501

    The version of the OpenAPI document: 0.25.5
    Contact: help@openziti.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openziti_edge_management
from openziti_edge_management.model.api_session_detail import ApiSessionDetail
globals()['ApiSessionDetail'] = ApiSessionDetail
from openziti_edge_management.model.api_session_list import ApiSessionList


class TestApiSessionList(unittest.TestCase):
    """ApiSessionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiSessionList(self):
        """Test ApiSessionList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiSessionList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
